// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArPlhGvR2_FbjktKpiEMQBaBmDOUugUgY',
    appId: '1:712156456078:web:ccbe507d3e228ed17ed5df',
    messagingSenderId: '712156456078',
    projectId: 'chat-app-23b78',
    authDomain: 'chat-app-23b78.firebaseapp.com',
    storageBucket: 'chat-app-23b78.appspot.com',
    measurementId: 'G-RHGSKHCY22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRlP8EgjIWtM-njBaKY9zBTudLv-jKHew',
    appId: '1:712156456078:android:eb3850015714318b7ed5df',
    messagingSenderId: '712156456078',
    projectId: 'chat-app-23b78',
    storageBucket: 'chat-app-23b78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRGZOCz2ekKTCekEF3Jace-FXDPjayvz0',
    appId: '1:712156456078:ios:d071cdbf12b1cb9d7ed5df',
    messagingSenderId: '712156456078',
    projectId: 'chat-app-23b78',
    storageBucket: 'chat-app-23b78.appspot.com',
    iosClientId: '712156456078-g0ku8gfsc2atjru1qqov5gpv8gdbqnoh.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppFirebase',
  );
}
